// Web Push client helpers: permission, subscription, and reminder prefs API.
// The service worker (generated by vite-plugin-pwa) carries the push handlers via
// public/push-handlers.js; here we just manage the subscription lifecycle.

const API_BASE = import.meta.env.VITE_API_URL ?? "http://localhost:8787";
const VAPID_PUBLIC = import.meta.env.VITE_VAPID_PUBLIC_KEY as string | undefined;

function urlBase64ToUint8Array(base64: string): Uint8Array {
  const padding = "=".repeat((4 - (base64.length % 4)) % 4);
  const b64 = (base64 + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(b64);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}

export function pushSupported(): boolean {
  return (
    typeof navigator !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window &&
    !!VAPID_PUBLIC
  );
}

async function currentSubscription(): Promise<PushSubscription | null> {
  const reg = await navigator.serviceWorker.ready;
  return reg.pushManager.getSubscription();
}

// Request permission, subscribe this device, persist to the API. Returns false if
// the user denied or push isn't available.
export async function enableReminders(reminderHour: number): Promise<boolean> {
  if (!pushSupported()) return false;
  const permission = await Notification.requestPermission();
  if (permission !== "granted") return false;

  const reg = await navigator.serviceWorker.ready;
  let sub = await reg.pushManager.getSubscription();
  if (!sub) {
    sub = await reg.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC!),
    });
  }
  const res = await fetch(`${API_BASE}/api/push/subscribe`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ subscription: sub.toJSON(), reminder_hour: reminderHour }),
  });
  return res.ok;
}

export async function disableReminders(): Promise<void> {
  const sub = await currentSubscription();
  if (!sub) return;
  await fetch(`${API_BASE}/api/push/unsubscribe`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ endpoint: sub.endpoint }),
  });
  await sub.unsubscribe();
}

export async function setReminderHour(reminderHour: number): Promise<void> {
  await fetch(`${API_BASE}/api/push/prefs`, {
    method: "PATCH",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ reminder_hour: reminderHour }),
  });
}

export async function getReminderPrefs(): Promise<{ enabled: boolean; hour: number }> {
  const res = await fetch(`${API_BASE}/api/push/prefs`, { credentials: "include" });
  if (!res.ok) return { enabled: false, hour: 8 };
  const j = (await res.json()) as { reminder_enabled?: boolean; reminder_hour?: number };
  return { enabled: !!j.reminder_enabled, hour: j.reminder_hour ?? 8 };
}
