// Web Push client helpers: permission, subscription, and reminder prefs API.
// The service worker (generated by vite-plugin-pwa) carries the push handlers via
// public/push-handlers.js; here we just manage the subscription lifecycle.

import { api } from "./api/client";

const VAPID_PUBLIC = import.meta.env.VITE_VAPID_PUBLIC_KEY as string | undefined;

function urlBase64ToUint8Array(base64: string): Uint8Array {
  const padding = "=".repeat((4 - (base64.length % 4)) % 4);
  const b64 = (base64 + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(b64);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}

export function pushSupported(): boolean {
  return (
    typeof navigator !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window &&
    !!VAPID_PUBLIC
  );
}

async function currentSubscription(): Promise<PushSubscription | null> {
  const reg = await navigator.serviceWorker.ready;
  return reg.pushManager.getSubscription();
}

// Request permission, subscribe this device, persist to the API. Returns false if
// the user denied or push isn't available.
export async function enableReminders(reminderHour: number): Promise<boolean> {
  if (!pushSupported()) return false;
  const permission = await Notification.requestPermission();
  if (permission !== "granted") return false;

  const reg = await navigator.serviceWorker.ready;
  let sub = await reg.pushManager.getSubscription();
  if (!sub) {
    sub = await reg.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC!),
    });
  }
  try {
    await api.post("/api/push/subscribe", { subscription: sub.toJSON(), reminder_hour: reminderHour });
    return true;
  } catch {
    return false;
  }
}

export async function disableReminders(): Promise<void> {
  const sub = await currentSubscription();
  if (!sub) return;
  // Best-effort server cleanup; always drop the local subscription regardless.
  await api.post("/api/push/unsubscribe", { endpoint: sub.endpoint }).catch(() => {});
  await sub.unsubscribe();
}

export async function setReminderHour(reminderHour: number): Promise<void> {
  await api.patch("/api/push/prefs", { reminder_hour: reminderHour });
}

export async function getReminderPrefs(): Promise<{ enabled: boolean; hour: number }> {
  try {
    const j = await api.get<{ reminder_enabled?: boolean; reminder_hour?: number }>("/api/push/prefs");
    return { enabled: !!j.reminder_enabled, hour: j.reminder_hour ?? 8 };
  } catch {
    return { enabled: false, hour: 8 };
  }
}
